# Generated by Django 3.0.14 on 2022-10-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, default='', max_length=50, verbose_name='Post')),
                ('username', models.CharField(blank=True, default='', max_length=30, verbose_name='Username')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
            ],
        ),
    ]
